version: '3.8'

services:
  access-control-fullstack:
    image: node:18-alpine
    ports:
      - "3000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:929d54bc0ff22387163f04cfb3b3d0fa@148.230.78.128:5432/controle
      - PGHOST=148.230.78.128
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=929d54bc0ff22387163f04cfb3b3d0fa
      - PGDATABASE=controle
      - PORT=5000
    working_dir: /app
    command: >
      sh -c "
      echo '🚀 Iniciando Access Control SaaS Full-Stack...' &&
      apk add --no-cache curl npm git python3 make g++ &&
      
      echo '📥 Clonando repositório completo...' &&
      git clone https://github.com/machisa/access.git . &&
      
      echo '📦 Instalando dependências...' &&
      npm install &&
      
      echo '🔧 Configurando sistema...' &&
      export NODE_ENV=production &&
      
      echo '🎯 Iniciando sistema completo...' &&
      npm run dev
      "
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 120s

networks:
  default:
    driver: bridge