version: '3.8'

services:
  web:
    image: node:18-alpine
    ports:
      - "3000:5000"
    environment:
      DATABASE_URL: postgresql://postgres:929d54bc0ff22387163f04cfb3b3d0fa@148.230.78.128:5432/controle
      PORT: 5000
      NODE_ENV: production
    working_dir: /app
    command: >
      sh -c "
      apk add --no-cache curl npm git &&
      git clone https://github.com/machisa/access.git . &&
      npm install &&
      npm run dev
      "
    deploy:
      replicas: 1
